version: '3'

services:
  nodejs-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: secret_key
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: practice
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: 123456
    depends_on:
      - postgres-db-1
      
  postgres-db-1:
    image: postgres:14.8 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: practice
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: 123456 
